# Site settings
author: casual-publisher-3309
title: 
header-img: img/home-bg.png
email: wandre94@gmail.com
copyright_name: casual-publisher-3309
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  william-ca

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
