# Site settings
author: William A.
title: Built by Will
header-img: img/home-bg.png
email: wandre94@gmail.com
copyright_name: William A.
description: > # this means to ignore newlines until "baseurl:"
  A humble collection of thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  william-ca

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
